import "./globals.css";
import ProviderTheme from "@/theme/ProviderTheme";
import { AppContextProvider } from "@/context/AppContext";

export const metadata = {
  title: "Event Wallet",
  // description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <head>
        <link rel="icon" href="/images/favicon.ico" />
      </head>
      <body>
        <AppContextProvider>
          <ProviderTheme>{children}</ProviderTheme>
        </AppContextProvider>
      </body>
    </html>
  );
}
