import "./globals.css";
import Providers from "@/theme/Providers";

export const metadata = {
  title: "Event Wallet",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
