import "./globals.css";
import Providers from "@/theme/Providers";
import { AppContextProvider } from "@/context/AppContext";

export const metadata = {
  title: "Event Wallet",
  // description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <AppContextProvider>
          <Providers>{children}</Providers>
        </AppContextProvider>
      </body>
    </html>
  );
}
